version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  auth-service:
    build: ./auth-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_REDIS_HOST=redis
    # Comment out volumes temporarily for testing
    # volumes:
    #   - ./auth-service:/app
    #   - ~/.m2:/root/.m2
    depends_on:
      - redis
    networks:
      - app-network

  shopping-service:
    build: ./shopping-service
    ports:
      - "8081:8081"
    # Comment out volumes temporarily for testing
    # volumes:
    #   - ./shopping-service:/app
    #   - ~/.m2:/root/.m2
    depends_on:
      - auth-service
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - auth-service
      - shopping-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 